[package]
name = "stop-goguardian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.23"

[profile.release]
lto = true
opt-level = "s"
